export let playerNames = ["Letters",
  "One",
  "Devil Soul",
  "BAD BOY",
  "Call Of Duty",
  "Tik Tok",
  "Aragon",
  "Kidnapper",
  "Facebook",
  "Viking",
  "Frozen",
  "Storm",
  "STOP",
  "Happy New Year",
  "Elephant",
  "Christmas",
  "Gondal",
  "Death Slayer",
  "Deep",
  "DarK Shadow",
  "Toy Story",
  "Co Owner",
  "IOS",
  "PUBG MOBILE",
  "Deadshot Akshat",
  "Good Day",
  "End",
  "Xpointy",
  "Cobra pavan",
  "STREAMER",
  "Salazar",
  "Spirit",
  "Avenger zeus",
  "Sticker",
  "Million Roses",
  "Moderator",
  "Roses",
  "Extraction",
  "God",
  "Lingojam",
  "Happy Birthday",
  "Start",
  "Nawaf",
  "Eagle shooter",
  "Kicker",
  "Verified",
  "Camper",
  "Smoker",
  "Ultimate",
  "Superman",
  "SWAT",
  "Clan",
  "PUBG MOBILE",
  "ALOK",
  "Christmas",
  "Black soul",
  "Storm breaker",
  "Witcher",
  "Pirates",
  "Titanic",
  "Ceremony",
  "Cobra pavan",
  "Sticker",
  "SAVAGE",
  "Titanium",
  "MAMY",
  "The BOSS",
  "ZEUS",
  "Nemo",
  "Dark Siders",
  "Symbol",
  "Sonic",
  "Deadshot Akshat",
  "Warriors",
  "Dark soul",
  "Poison",
  "Race",
  "God",
  "CRIMINAL",
  "Storm",
  "Mafia",
  "Relax",
  "Eternal",
  "CRAZY",
  "Merci",
  "Brand",
  "Titanic",
  "Android",
  "Elephant",
  "White Walker",
  "Start",
  "NOOB",
  "Furious",
  "Agent 47",
  "SAFAH",
  "Time",
  "Toy Story",
  "Million Roses",
  "IOS",
  "Big boss",
  "Wedding",
  "Devil",
  "Zpointy",
  "Hero prince",
  "Heidern",
  "Wizard",
  "Fury",
  "Crusher",
  "Chaser",
  "Thor",
  "Mafia",
  "Cobra pavan",
  "VIP Gamers",
  "Ideas",
  "Dark Siders",
  "UNKNOWN",
  "Virus",
  "Venom",
  "Mom",
  "General",
  "MAMY"
]

export let serverNames = ["Giant Factions",
  "Combat Nation",
  "Spartan Warzone",
  "Destroy Build",
  "Spooky sVanilla",
  "Storm Roleplay",
  "Dusk Worlds",
  "Hero Factions",
  "1337 Factions",
  "Raiding Economy",
  "Storm Mining",
  "Infinite Hardcore",
  "Apoc Time",
  "Blocky Dimension",
  "Green RPG",
  "Construct Assault",
  "Modded Nation",
  "Super Galaxy",
  "Archer Realms",
  "Place Wars",
  "Post-Apocalyptic Bukkit",
  "High-Tech Wars",
  "Desert Survival",
  "Combat Bukkit",
  "Sparta Galaxy",
  "Waffle Outpost",
  "Tree Worlds",
  "Dawn Warzone",
  "Deadly Town",
  "Evil Gasm",
  "Winter Universe",
  "Robot Adventures",
  "Twilight Haven",
  "Dangerous Galaxy",
  "Simple Roleplay",
  "Apocalyptic CTF",
  "Noble Haven",
  "Massacre Town",
  "Bedrock Lands",
  "Apocalypse PvE",
  "RPG Lands",
  "Hell PvE",
  "Standard Haven",
  "Shelter Craft",
  "Supernatural City",
  "Supernatural Survival",
  "Danger Legends",
  "RPG Build",
  "Blocky Bukkit",
  "Archer Clan",
  "Prison Universe",
  "Shelter Tekkit",
  "Undead Adventures",
  "Electronic Realms",
  "Infinity Creative",
  "Mine PvP/Raid",
  "Mine Vanilla",
  "Noble Hardcore",
  "High-Tech Worlds",
  "Faction Gasm",
  "Warrior Kingdoms",
  "FPS Survival",
  "Tech MC",
  "Spartans Hell",
  "Metro Roleplay",
  "Chaos PvE",
  "Unlimited Games",
  "Nether World",
  "Creeper Land",
  "My World",
  "Evil Games",
  "Magma Worlds",
  "Universe Lands",
  "Super City",
  "Infinite Craft",
  "Massacre Club",
  "Apocalypse Nation",
  "Pork Army",
  "Super Empire",
  "Wood Land",
  "Redstone Legends",
  "Factory Outpost",
  "Hunt City",
  "Massacre Universe",
  "Spooky Haven",
  "Waffle RPG",
  "Place Clan",
  "Unknown Server",
  "Sandstone Factions",
  "Pancake Society",
  "Murder Scape",
  "Stone Galaxy",
  "Best sVanilla",
  "Brutal Realm",
  "Redstone Lands",
  "Construct Games",
  "Hope Mine",
  "Reflex Town",
  "Infinite Outpost",
  "Bedrock Server",
  "Epicness Survival"
]